link : utils.o array.o main2.o
	gcc utils.o array.o main2.o -o array.exe

utils.o :
	gcc -c utils.c

array.o :
	gcc -c array.c

main2.o :
	gcc -c main2.c

clean :
	rm -f utils.o array.o main2.o array.exe
